add required name attribute
Starting Chef Client, version 12.8.1
[...]
ERROR: Cookbook loaded at path(s) [~/chef-solo/cookbooks-1/chef-shorewall] has invalid metadata: The `name' attribute is required in cookbook metadata